# Dockerfile.dev (Modificado)

FROM rust

WORKDIR /app

RUN cargo install cargo-watch

COPY Cargo.toml Cargo.lock ./

RUN mkdir src && echo "fn main() {}" > src/main.rs
RUN cargo build

COPY . .

# CAMBIO CLAVE: Añadir --poll al comando
CMD ["cargo", "watch", "-x", "run", "--poll"]
